-- USERS
CREATE TABLE USERS (
    ID NUMBER(20, 2) NOT NULL PRIMARY KEY,
    CREATE_DATE DATE NULL,
    ACCOUNT_NUM VARCHAR2(255) NULL,
    ADDRESS VARCHAR2(255) NULL,
    ADDRESS_DETAIL VARCHAR2(255) NULL,
    ZIP_CODE VARCHAR2(255) NULL,
    EMAIL VARCHAR2(255) NULL,
    NAME VARCHAR2(255) NULL,
    LOGIN_ID VARCHAR2(255) NULL,
    PASSWORD VARCHAR2(255) NULL,
    PHONE VARCHAR2(255) NULL,
    REFRESH_TOKEN VARCHAR2(255) NULL,
    SIMPLE_PASSWORD VARCHAR2(255) NULL,
    IS_ADMIN NUMBER(1, 2) NULL
);

-- BANK_PRODUCT
CREATE TABLE BANK_PRODUCT (
    ID NUMBER(8, 2) NOT NULL PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    IMG VARCHAR2(255) NULL,
    DESCRIPTION VARCHAR2(1000) NULL,
    CATEGORY VARCHAR2(100) NULL,
    BENEFITS VARCHAR2(1000) NULL,
    INTEREST NUMBER(5, 2) NULL,
    TYPE VARCHAR2(50) NULL
);

-- USER_ACCOUNT (복합 PK + FK)
CREATE TABLE USER_ACCOUNT (
    USER_ID NUMBER(8, 2) NOT NULL,
    ACCOUNT_ID NUMBER(8, 2) NOT NULL,
    ACCOUNT_NUMBER VARCHAR2(30) NOT NULL,
    ACCOUNT_NAME VARCHAR2(100) NULL,
    PRIMARY KEY (USER_ID, ACCOUNT_ID),
    CONSTRAINT USER_ACCOUNT_ACCOUNT_NUMBER_UQ UNIQUE (ACCOUNT_NUMBER),
    CONSTRAINT USER_ACCOUNT_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT USER_ACCOUNT_ACCOUNT_ID_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES BANK_PRODUCT(ID)
);

-- CARD_PRODUCT
CREATE TABLE CARD_PRODUCT (
    ID NUMBER(8, 2) NOT NULL PRIMARY KEY,
    IMG VARCHAR2(255) NULL,
    NAME VARCHAR2(100) NOT NULL,
    BRAND VARCHAR2(50) NULL,
    DESCRIPTION VARCHAR2(1000) NULL,
    CATEGORY VARCHAR2(100) NULL,
    BENEFITS VARCHAR2(1000) NULL,
    INTEREST NUMBER(5, 2) NULL,
    TYPE VARCHAR2(50) NULL
);

-- USER_CARD (복합 PK + FK)
CREATE TABLE USER_CARD (
    USER_ID NUMBER(8, 2) NOT NULL,
    CARD_ID NUMBER(8, 2) NOT NULL,
    PRIMARY KEY (USER_ID, CARD_ID),
    CONSTRAINT USER_CARD_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT USER_CARD_CARD_ID_FK FOREIGN KEY (CARD_ID) REFERENCES CARD_PRODUCT(ID)
);

-- NYANG_COIN
CREATE TABLE NYANG_COIN (
    ID NUMBER(20, 2) NOT NULL PRIMARY KEY,
    CREATE_DATE DATE NULL,
    MONEY NUMBER(20, 2) NULL,
    USER_ID NUMBER(20, 2) NULL,
    CONSTRAINT NYANG_COIN_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- TRANSACTION
CREATE TABLE TRANSACTION (
    ID NUMBER(20, 2) NOT NULL PRIMARY KEY,
    APPROVED_AMOUNT NUMBER(20, 2) NULL,
    APPROVED_NUM VARCHAR2(255) NULL,
    CARD_HISTORY_ID NUMBER(20, 2) NULL,
    CARD_ID NUMBER(20, 2) NULL,
    CARD_TYPE VARCHAR2(255) NULL,
    CATEGORY VARCHAR2(255) NULL,
    DATE_TIME DATE NULL,
    SHOP_NAME VARCHAR2(255) NULL,
    SHOP_NUMBER VARCHAR2(255) NULL,
    USER_ID NUMBER(20, 2) NULL,
    CONSTRAINT TRANSACTION_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- COIN_HISTORY
CREATE TABLE COIN_HISTORY (
    ID NUMBER(20, 2) NOT NULL PRIMARY KEY,
    CREATE_DATE DATE NULL,
    TOTAL_AMT NUMBER(20, 2) NULL,
    TRANS_AMT NUMBER(20, 2) NULL,
    TRANS_TYPE VARCHAR2(255) NULL,
    NYANG_ID NUMBER(20, 2) NULL,
    CONSTRAINT COIN_HISTORY_NYANG_ID_FK FOREIGN KEY (NYANG_ID) REFERENCES NYANG_COIN(ID)
);

-- ADMIN
CREATE TABLE ADMIN (
    ID NUMBER(20, 2) NOT NULL PRIMARY KEY,
    USER_ID NUMBER(20, 2) NULL UNIQUE,
    ROLE VARCHAR2(50) NULL,
    CREATE_DATE DATE NULL,
    CONSTRAINT ADMIN_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- INDUSTRY_CODES
CREATE TABLE INDUSTRY_CODES (
    UPJONG_CODE VARCHAR2(20) NOT NULL PRIMARY KEY,
    UPJONG VARCHAR2(100) NULL
);

-- GENDER_STATS
CREATE TABLE GENDER_STATS (
    ID NUMBER(8, 2) NOT NULL PRIMARY KEY,
    UPJONG_CODE VARCHAR2(20) NULL,
    YEARMONTH DATE NULL,
    GENDER VARCHAR2(10) NULL,
    CARD_TOTAL NUMBER(8, 2) NULL,
    CONSTRAINT GENDER_STATS_UPJONG_CODE_FK FOREIGN KEY (UPJONG_CODE) REFERENCES INDUSTRY_CODES(UPJONG_CODE)
);

-- AGE_STATS
CREATE TABLE AGE_STATS (
    ID NUMBER(8, 2) NOT NULL PRIMARY KEY,
    UPJONG_CODE VARCHAR2(20) NULL,
    YEARMONTH DATE NULL,
    AGE_GROUP VARCHAR2(20) NULL,
    CARD_TOTAL NUMBER(8, 2) NULL,
    CONSTRAINT AGE_STATS_UPJONG_CODE_FK FOREIGN KEY (UPJONG_CODE) REFERENCES INDUSTRY_CODES(UPJONG_CODE)
);

-- MICRO_PAYMENT_STATS
CREATE TABLE MICRO_PAYMENT_STATS (
    ID NUMBER(8, 2) NOT NULL PRIMARY KEY,
    UPJONG_CODE VARCHAR2(20) NULL,
    YEARMONTH DATE NULL,
    TIME_SLOT VARCHAR2(20) NULL,
    CARD_TOTAL NUMBER(8, 2) NULL,
    CONSTRAINT MICRO_PAYMENT_STATS_UPJONG_CODE_FK FOREIGN KEY (UPJONG_CODE) REFERENCES INDUSTRY_CODES(UPJONG_CODE)
);

-- REGION_STATS
CREATE TABLE REGION_STATS (
    ID NUMBER(8, 2) NOT NULL PRIMARY KEY,
    UPJONG_CODE VARCHAR2(20) NULL,
    SIDO VARCHAR2(20) NULL,
    SIGUNGU VARCHAR2(20) NULL,
    UPJONG VARCHAR2(50) NULL,
    YEARMONTHDATE DATE NULL,
    TOTAL_ADDRESS_CODE VARCHAR2(20) NULL,
    CARD_TOTAL NUMBER(8, 2) NULL,
    CONSTRAINT REGION_STATS_UPJONG_CODE_FK FOREIGN KEY (UPJONG_CODE) REFERENCES INDUSTRY_CODES(UPJONG_CODE)
);
